database:
  host: localhost
  port: 3306
  database: playerdata
  user:
  password:
clovers:
  y-level: 73
  debug-generation: false
  # maxClovers is the maximum amount of clovers that can spawn without the bonus.
  # maxCloverBonus is, you guessed it, the maximum bonus.
  maxClovers: 20
  maxCloverBonus: 5
  # This is the chance, in percent, for each clover to turn into a four-leaf clover.
  fourLeafChance: 0.5
lottery:
  # These are chances, in percent, for a certain color marble to be rolled in the lottery.
  # If the sum of these values surpasses 100, default values will be used instead.
  gold: 3
  red: 6
  green: 9
  blue: 16
other:
  # Adjusts the chances for a bonus ticket to be awarded upon buying items. This number is in percent.
  shopBonus: 20